---
name: general

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  general:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep random
        uses: 1itachi/sleep-random@v1.0.0
        with:
          minutes: '1'
          random: 'true'

...
